/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 08-05-2015
 * 
 * XDoclet definition:
 * @struts.form name="createprojectForm"
 */
public class CreateprojectForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	private FormFile image1,image2,image3;
	private String submit,fileName;
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public FormFile getImage1() {
		return image1;
	}

	public void setImage1(FormFile image1) {
		this.image1 = image1;
	}

	public FormFile getImage2() {
		return image2;
	}

	public void setImage2(FormFile image2) {
		this.image2 = image2;
	}

	public FormFile getImage3() {
		return image3;
	}

	public void setImage3(FormFile image3) {
		this.image3 = image3;
	}

	public String getSubmit() {
		return submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}
		
}