/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 08-12-2015
 * 
 * XDoclet definition:
 * @struts.form name="createprojectForm"
 */
public class CreateprojectForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private static final long serialVersionUID = 2025885369419610335L;
	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	private String bu_no,bu_name;
	private FormFile uploadedFile = null;
	private String fileName = null;

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public FormFile getUploadedFile() {
		return uploadedFile;
	}

	public void setUploadedFile(FormFile uploadedFile) {
		this.uploadedFile = uploadedFile;
	}
	public String getBu_no() {
		return bu_no;
	}

	public void setBu_no(String buNo) {
		bu_no = buNo;
	}

	public String getBu_name() {
		return bu_name;
	}

	public void setBu_name(String buName) {
		bu_name = buName;
	}

	public CreateprojectForm(String buNo, String buName) {
		// TODO Auto-generated constructor stub
		this.bu_no = buNo;
		this.bu_name = buName;
	}
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}