/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.smict.struts.form.AfterchooseForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-14-2015
 * 
 * XDoclet definition:
 * @struts.action path="/afterchoose" name="afterchooseForm" input="/afterchoose.jsp" scope="request" validate="true"
 */
public class AfterchooseAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AfterchooseForm afterchooseForm = (AfterchooseForm) form;// TODO Auto-generated method stub
		List testchk = new ArrayList();
//		String[] namechk = new String[6];
//		for(int i = 1 ; i<=5;i++){
//			
//			namechk[i] = "chk"+i;
//		}
		for(int i = 1 ; i<=5;i++){
			testchk.add(request.getParameter("chk"+i));
		}
		
		return null;
	}
}