/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smict.struts.data.DBuser;
import com.smict.struts.form.CreateuserForm;

import java.io.UnsupportedEncodingException;
import java.util.*;

/** 
 * MyEclipse Struts
 * Creation date: 10-06-2015
 * 
 * XDoclet definition:
 * @struts.action path="/createuser" name="createuserForm" input="/form/createuser.jsp" scope="request" validate="true"
 */
public class CreateuserAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CreateuserForm createuserForm = (CreateuserForm) form;
		DBuser dbuser = new DBuser();
		String forwardText = "success";
		String firstname = null, lastname = null, username = null, position = null;
		try {
			firstname = new String (request.getParameter("tb_firstname").getBytes("ISO-8859-1"),"UTF-8");
			lastname = new String (request.getParameter("tb_lastname").getBytes("ISO-8859-1"),"UTF-8");
			username = request.getParameter("tb_username");
			position = request.getParameter("slc_position");
		} catch (UnsupportedEncodingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		boolean insert_success = true;
		try {
			insert_success = dbuser.Createuser(firstname, lastname, username, position);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if(!insert_success){
			forwardText = "false";
		}
		return mapping.findForward(forwardText);
	}
}