/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.action;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.smict.struts.data.DBProject;
import com.smict.struts.form.BusinessForm;;

/** 
 * MyEclipse Struts
 * Creation date: 08-19-2015
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class EditprojectStartAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		String forwardText = "";
		if(session.getAttribute("username") == null){
			forwardText = "nologin";
		}else{
			DBProject dbpro = new DBProject();
			forwardText = "success";
			List projectList = null;
			try {
				projectList =dbpro.projectList();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			request.setAttribute("projectList", projectList);
		}
		return mapping.findForward(forwardText);
	}
}