/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.smict.struts.form.IndexVSAForm;
import com.smict.struts.data.DBProject;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2015
 * 
 * XDoclet definition:
 * @struts.action path="/indexVSA" name="indexVSAForm" scope="request" validate="true"
 */
public class IndexVSAAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		IndexVSAForm indexVSAForm = (IndexVSAForm) form;// TODO Auto-generated method stub
		DBProject dbpj = new DBProject();
		List indexList = dbpj.Get_HeaderProjectForIndex("VSA");
		request.setAttribute("indexList", indexList);
		return mapping.findForward("success");
	}
}