/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vsa.struts.action;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.vsa.struts.form.CreateprojectForm;
import com.vsa.struts.data.DBProject;
/** 
 * MyEclipse Struts
 * Creation date: 08-11-2015
 * 
 * XDoclet definition:
 * @struts.action path="/createprojectStart" name="createprojectForm" scope="request" validate="true"
 * @struts.action-forward name="success" path="/createproject.jsp"
 */
public class CreateprojectStartAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CreateprojectForm createprojectForm = (CreateprojectForm) form;
		DBProject dbproject = new DBProject();
		String forwardText = "";
		// TODO Auto-generated method stub
		try {
			List buList = dbproject.bu_nameList();
			request.setAttribute("buList", buList);
			forwardText = "success";
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return mapping.findForward(forwardText);
	}
}