/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 10-19-2015
 * 
 * XDoclet definition:
 * @struts.form name="awardForm"
 */
public class AwardForm extends ActionForm {
	/**
	 * 
	 */
	private FormFile uploadedFile = null;
	private String awardpicpath,awardname,buname;
	public AwardForm(){}
	public AwardForm(String awardPicpath, String buName, String awardName) {
		this.awardpicpath = awardPicpath;
		this.buname = buName;
		this.awardname = awardName;
	}
	public FormFile getUploadedFile() {
		return uploadedFile;
	}
	public void setUploadedFile(FormFile uploadedFile) {
		this.uploadedFile = uploadedFile;
	}
	public String getAwardpicpath() {
		return awardpicpath;
	}
	public void setAwardpicpath(String awardpicpath) {
		this.awardpicpath = awardpicpath;
	}
	public String getAwardname() {
		return awardname;
	}
	public void setAwardname(String awardname) {
		this.awardname = awardname;
	}
	public String getBuname() {
		return buname;
	}
	public void setBuname(String buname) {
		this.buname = buname;
	}
}