/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-13-2015
 * 
 * XDoclet definition:
 * @struts.form name="businessForm"
 */
public class BusinessForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	private String bu_no,bu_name;
	
	public BusinessForm(){}
	public BusinessForm(String forwhat,String bu_no,String bu_name){
		if(forwhat.equals("slc_bu")){
			this.bu_no = bu_no;
			this.bu_name = bu_name;
		}
	}
	
	public String getBu_no() {
		return bu_no;
	}

	public void setBu_no(String buNo) {
		bu_no = buNo;
	}

	public String getBu_name() {
		return bu_name;
	}

	public void setBu_name(String buName) {
		bu_name = buName;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}