/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2015
 * 
 * XDoclet definition:
 * @struts.form name="indexVSAForm"
 */
public class IndexVSAForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String pj_name,pj_year,pj_typename,pic_path;

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	IndexVSAForm() {
	}
	
	public IndexVSAForm(String pj_name, String pj_year, String pj_typename,
			String pic_path) {
		this.pj_name = pj_name;
		this.pj_year = pj_year;
		this.pj_typename = pj_typename;
		this.pic_path = pic_path;
	}

	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	public String getPj_name() {
		return pj_name;
	}

	public void setPj_name(String pjName) {
		pj_name = pjName;
	}

	public String getPj_year() {
		return pj_year;
	}

	public void setPj_year(String pjYear) {
		pj_year = pjYear;
	}

	public String getPj_typename() {
		return pj_typename;
	}

	public void setPj_typename(String pjTypename) {
		pj_typename = pjTypename;
	}

	public String getPic_path() {
		return pic_path;
	}

	public void setPic_path(String picPath) {
		pic_path = picPath;
	}
}