/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.smict.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 10-05-2015
 * 
 * XDoclet definition:
 * @struts.form name="nortificationsForm"
 */
public class NortificationsForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String norti_id,norti_from,norti_email,norti_message,norti_s,norti_sname,bu_no,bu_name,timestamp;
	
	private String count_noti_id;
	
	NortificationsForm() {}
	public NortificationsForm(String forwhat, String s1, String s2,
			String s3, String s4, String s5, String s6,
			String s7, String s8, String s9) {
		if(forwhat.equals("shownorti")){
			norti_id = s1;
			norti_from = s2;
			norti_email = s3;
			norti_message = s4;
			norti_s = s5;
			norti_sname = s6;
			bu_no = s7;
			bu_name = s8;
			timestamp = s9;			
		}
	}

	public NortificationsForm(String forwhat, String s1, String s2) {
		if(forwhat.equals("CountNotifications_NotRead")){
			this.bu_no = s1;
			this.count_noti_id = s2;
		}
	}
	public String getCount_noti_id() {
		return count_noti_id;
	}
	public void setCount_noti_id(String countNotiId) {
		count_noti_id = countNotiId;
	}
	public String getNorti_id() {
		return norti_id;
	}

	public void setNorti_id(String nortiId) {
		norti_id = nortiId;
	}

	public String getNorti_from() {
		return norti_from;
	}

	public void setNorti_from(String nortiFrom) {
		norti_from = nortiFrom;
	}

	public String getNorti_email() {
		return norti_email;
	}

	public void setNorti_email(String nortiEmail) {
		norti_email = nortiEmail;
	}

	public String getNorti_message() {
		return norti_message;
	}

	public void setNorti_message(String nortiMessage) {
		norti_message = nortiMessage;
	}

	public String getNorti_s() {
		return norti_s;
	}

	public void setNorti_s(String nortiS) {
		norti_s = nortiS;
	}

	public String getNorti_sname() {
		return norti_sname;
	}

	public void setNorti_sname(String nortiSname) {
		norti_sname = nortiSname;
	}

	public String getBu_no() {
		return bu_no;
	}

	public void setBu_no(String buNo) {
		bu_no = buNo;
	}

	public String getBu_name() {
		return bu_name;
	}

	public void setBu_name(String buName) {
		bu_name = buName;
	}

	public String getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}